### ISSUE TITLE
It is recommended that rules be summarized and classified and applicable scenarios of rules be provided.

### ISSUE THREAD

**Issue by onemoreflag** [quark-engine/quark-rules#1]
for example
![image](https://user-images.githubusercontent.com/48425509/101706175-86d3e700-3ac3-11eb-91b9-0508119abd4b.png)
:-)
:-P
;-)

**Comment by 18z** [comment]
Hi @onemoreflag,

Thank you for the suggestion.
Actually, we are designing rule management system just like this https://bit.ly/36KlxGL.
More improvement are coming. :D
Stay tuned!
